name: CI

on: [push, pull_request]

jobs:
  build:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, macos, windows ]
        ruby: [ 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, head ]
        include:
          - { os: windows, ruby: mingw }
        exclude:
          - { os: windows, ruby: head }
    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: load ruby, openssl
        uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          mingw: _upgrade_ openssl

      - name: macOS disable firewall 
        if: startsWith(matrix.os, 'macos')
        run: |
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate

      - name: bundle install
        run:  bundle install --jobs 4 --retry 3 --without=documentation

      - name: compile
        run:  bundle exec rake compile

      - name: test
        run:  bundle exec rake test
        env:
          CI: true
          TESTOPTS: -v --no-show-detail-immediately
